.TH CHIP8ASM 1 "2024-08-14" \VERSION "CHIP-8 Interpreter Manual"

.SH NAME
chip8asm \- A CHIP-8 interpreter written in x64 Linux NASM assembly and Raylib

.SH SYNOPSIS
.B chip8asm
.I [ROM file]

.SH DESCRIPTION
.B chip8asm
is a fully functional interpreter for the CHIP-8 programming language, 
meticulously crafted in assembly language. CHIP-8, originally designed in the
1970s, is a simple, "low-level" programming language used for creating games
on early computer systems. The goal of this interpreter is to bring back the 
nostalgia and charm of CHIP-8, providing a modern implementation while 
preserving the essence of the original.

.SH FEATURES
This interpreter is based on well-documented references, such as Cowgod's 
Chip-8 Technical Reference and Mastering CHIP-8. In addition to faithfully 
reproducing the CHIP-8 instruction set, several enhancements have been made to 
improve performance:

.TP
.B Timing
Raylib has been configured to aim for 200 FPS, which means that 200 instructions
are executed per second, but also managing to update timers update at their 
correct frequency (60Hz). This is done with the intention of providing a 
smoother user experience.

.TP
.B Sound
This interpreter has sound support for programs that use the delay timer to 
play the CHIP-8 beep sound. This sound has been generated thanks to
onlinetonegenerator.com using a 440Hz frequency and a square wave.

.SH RUN
To run a ROM file that contains a CHIP-8 program, you need the chip8asm 
executable to run it. You can obtain it via compiling the project and 
installing it, or from any of the releases at the releases page. After that, 
you can run CHIP-8 compatible ROMs using this interpreter.

Some sources for ROMs are:
.TP
.B https://github.com/kripod/chip8-roms
.TP
.B https://www.zophar.net/pdroms/chip8.html
.TP
.B https://chipo.ber.gp/
.TP
.B https://johnearnest.github.io/chip8Archive/

.TP
.B Important
The program does not care about the file extension (some sites may use .c8, 
.ch8, etc), but it checks if the file size is small enough to fit inside the 
read-only segment of the CHIP-8 memory (The maximum file size is 3584 (0xE00)
bytes, given by the addresses 0x200 - 0xFFF).

.SH USAGE
.B
.IR "chip8asm some/directory/to/rom"

.SH LICENSE
.B chip8asm
is free and distributed under the GNU General Public License version 3 (GPL v3).
Essentially, this means you are free to do almost exactly what you want with 
the program, including distributing it among your friends, making it available
for download from your website, selling it (either by itself or as part of some
bigger software package), or using it as the starting point for a software
project of your own.

The only real limitation is that whenever you distribute chip8asm in some way, 
you MUST always include the license and the full source code (or a pointer to 
where the source code can be found) to generate the exact binary you are 
distributing. If you make any changes to the source code, these changes must 
also be made available under GPL v3.
